name: Run tests
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

env:
  THIRD_PARTY_DIR: "$GITHUB_WORKSPACE/3rdParty"

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
    - uses: actions/checkout@main
      with:
        repository: biomedia-mira/stitching   
        ref: ${{ github.event.inputs.git_ref || 'd31242797e0438c5de7f5fc69b14697f71c090d5' }} 

    - name: Build dependencies, then build `stitching`
      run: |
        # prepare 3-party libs
        mkdir ${{ env.THIRD_PARTY_DIR }}

        # get Eigen
        cd ${{ env.THIRD_PARTY_DIR }}
        wget https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.gz --progress=bar:force:noscroll
        mkdir eigen
        tar xf eigen-3.3.7.tar.gz -C eigen --strip-components=1

        # download and install boost
        cd ${{ env.THIRD_PARTY_DIR }}
        wget https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.gz --progress=bar:force:noscroll
        tar xf boost_1_80_0.tar.gz
        cd boost_1_80_0/
        # build Boost
        ./bootstrap.sh
        ./b2
        # point cmake at the location of the various boost cmake files
        export CMAKE_PREFIX_PATH=../3rdParty/boost_1_80_0/stage/lib/cmake/

        # download and install ITK
        cd ${{ env.THIRD_PARTY_DIR }}
        wget https://sourceforge.net/projects/itk/files/itk/5.0/InsightToolkit-5.0.0.tar.gz --progress=bar:force:noscroll
        tar xf InsightToolkit-5.0.0.tar.gz
        cd InsightToolkit-5.0.0
        mkdir build
        cd build
        cmake \
            -DBUILD_EXAMPLES:BOOL=OFF \
            -DBUILD_TESTING:BOOL=OFF \
            -DCMAKE_INSTALL_PREFIX=${{ env.THIRD_PARTY_DIR }}/itk \
          ..
        make -j$(nproc)
        make install

        # build `stitching`
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)
