name: Run tests
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@main
      with:
        name: biomedia-mira/stitching   
        ref: refs/heads/release
    - name: run bash script 
      run: |
        cd stitching
        /bin/bash build.sh