name: Run tests
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@master
        with:
          name: iomedia-mira/stitching   
          ref: refs/heads/release
      - name: run bash script 
        run: |
          cd stitching
          /bin/bash build.sh