name: Run tests
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

env:
  THIRD_PARTY_DIR: "$GITHUB_WORKSPACE/3rdParty"

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
    - uses: actions/checkout@main
      with:
        repository: biomedia-mira/stitching   
        ref: ${{ github.event.inputs.git_ref || 'd31242797e0438c5de7f5fc69b14697f71c090d5' }} 

    - name: Download Eigen
      run: |
        mkdir ${{ env.THIRD_PARTY_DIR }}
        cd ${{ env.THIRD_PARTY_DIR }}
        wget https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.gz --progress=bar:force:noscroll
        mkdir eigen
        tar xf eigen-3.3.7.tar.gz -C eigen --strip-components=1

    - name: Download and build Boost
      run: |
        cd ${{ env.THIRD_PARTY_DIR }}
        wget https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.gz --progress=bar:force:noscroll
        tar xf boost_1_80_0.tar.gz
        cd boost_1_80_0/
        # build Boost
        ./bootstrap.sh
        ./b2 link=static

    - name: Ensure static linking of Boost libraries
      run: |
        # See: https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3865#discussion_r957565175
        echo "" >> itkio/cmake/FindConfig.cmake
        echo "set(Boost_USE_STATIC_LIBS ON)" >> itkio/cmake/FindConfig.cmake
        echo "" >> stitching/cmake/FindConfig.cmake
        echo "set(Boost_USE_STATIC_LIBS ON)" >> stitching/cmake/FindConfig.cmake

    - name: Download and build ITK
      run: |
        cd ${{ env.THIRD_PARTY_DIR }}
        wget https://sourceforge.net/projects/itk/files/itk/5.0/InsightToolkit-5.0.0.tar.gz --progress=bar:force:noscroll
        tar xf InsightToolkit-5.0.0.tar.gz
        cd InsightToolkit-5.0.0
        mkdir build
        cd build
        cmake \
            -DBUILD_EXAMPLES:BOOL=OFF \
            -DBUILD_TESTING:BOOL=OFF \
            -DCMAKE_INSTALL_PREFIX=${{ env.THIRD_PARTY_DIR }}/itk \
          ..
        make -j$(nproc)
        make install

    - name: Build stitching
      run: |
        export THIRD_PARTY_DIR=${{ env.THIRD_PARTY_DIR }}
        export ITK_DIR=${{ env.THIRD_PARTY_DIR }}/InsightToolkit-5.0.0/build
        export CMAKE_PREFIX_PATH=${{ env.THIRD_PARTY_DIR }}/boost_1_80_0/stage/lib/cmake/
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)

    - name: Verify dynamic linking
      run: ldd build/stitching/stitching

    - name: Package files
      run: |
        mkdir archive
        cp build/stitching/stitching archive
        mkdir archive/copyright
        cp LICENSE archive/copyright/LICENSE_stitching.txt
        tar -zcvf stitching_linux.tar.gz archive/

    - name: Upload packaged archive
      uses: actions/upload-artifact@v2-preview
      with:
        name: stitching_linux
        path: stitching_linux.tar.gz
